### PR TITLE
Feat/show dex contract

### LINKED ISSUE #148: info about `add_liquidity` and `remove_liquidity`
we should display DEX related contract calls for `add_liquidity` the same way like we do it for token transfers and change allowance already.

@kenodressel @bogdan-manole I saw there is `add_liquidity` and `add_liquidity_ae` as well as `remove_liquidity` and `remove_liquidity_ae`. what's the reason for that? should we distinguish in the explorer or treat both the same?

image

### LINKED ISSUE #149: info about DEX swaps
we should display DEX related contract calls for swaps the same way like we do it for token transfers and change allowance already.

we have many different swap entrypoints again, see https://github.com/aeternity/dex-contracts-v2/blob/master/contracts/interfaces/router/IAedexV2Router.aes#L64

@kenodressel @bogdan-manole what do you think about the display in the explorer? do we need to treat those differently?

### PR DESCRIPTION
**Pull request by ifaouibadi**
**What**
show DEX contract interactions in the tx-overview

**Why**
Fixes #148 
Fixes #149

### CODE REVIEW

**Comment by marc0olo** [comment]
@ifaouibadi I have one transaction on testnet where the tx got reverted and "SWAP" isn't displayed for some reason 🤔 

account: http://localhost:3000/account/ak_gZ55FLJoGEfF5gJ2xJU7j9uSH3fEjoTZq3ygQG8gYA4no6GFW
tx: http://localhost:3000/transactions/th_NHw51M5V4RgchV129CeKZc61wbCZ18DJPWosPm58VADqb4JsY

can you check that? or is this intentionally because it reverted? it would at least good to know what the failed tx was about

**Comment by marc0olo** [comment]
image

seems like duplicate information to me. I think the display that links to the token-view is sufficient =)

**Comment by marc0olo** [comment]
image

this is not relevant for the swap and kind of missleading information. I think we shouldn't display anything here. it's sufficient to see the amount of tokens sent and received

**Comment by marc0olo** [comment]
image

it's about following two transactions:
- http://localhost:3000/transactions/th_2WPt9cmRNrCdXh19UnC95QHvBbXE8H7797Uv3zB6JgKJC9KeYQ
- http://localhost:3000/transactions/th_2aHhuMMcmUj6jzjJRJ2qfxqvnmeXnJVuKQgeMWzXhy6BzqmMVc

I am quite confused in this display. following things:

1. I think we shouldn't differentiate between `ADD_LIQUIDITY_AE` and `ADD_LIQUIDITY` for the user (same for remove liquidity if this is the case) - kind of confusing for the average joe 😅 
2. I am not sure if the values are correct, maybe @bogdan-manole or @kenodressel can provide feedback on what and how we should display this best

**Review by marc0olo — CHANGES_REQUESTED** [review]
image

an you please find out and clarify with @bogdan-manole and/or @kenodressel what we should display on the explorer for the add_liquidity entrypoints?

I know we have two different entrypoints for `AE + token` vs. `token + token` but generally we should display the information in the details of the tx correctly. "from amount" and "to amount" is not sufficient and even missleading for **add liquidity**.

here are the function calls in the contract sourcecode:
- https://github.com/aeternity/dex-contracts-v2/blob/master/contracts/router/AedexV2Router.aes#L77

as params we have following that might be worth to display:
- token a (or AE)
- token b
- amount token a (disired and minimum)
- amount token b (desired and minimum)

also there will be probably a "real amount" for both tokens - not sure if you can get that information from the transaction.

**Comment by bogdan-manole** [comment]
> also there will be probably a "real amount" for both tokens - not sure if you can get that information from the transaction.

The `add_liquidity` and `add_liquidity_ae` are returning `( amount_a, amount_b, minted_liquidity )` Representing the real amount for the tokens added and the real liquidity token received in exchange for that. Don’t know if that can be  used / seen here

**Comment by marc0olo** [comment]
thanks Bogdan, should have checked the code more closely. I see it's being returned. we can definitely show this :)

**Comment by bogdan-manole** [comment]
> thanks Bogdan, should have checked the code more closely. I see it's being returned. we can definitely show this :)

My stupid question here is if we know at this point how many decimals every token uses in real life in order to be shown as such. We know that the liquidity token has 18 decimals, but what about the tokens which are used to add the liquidity, can we access the `meta_info` ?

**Comment by marc0olo** [comment]
> My stupid question here is if we know at this point how many decimals every token uses in real life in order to be shown as such. We know that the liquidity token has 18 decimals, but what about the tokens which are used to add the liquidity, can we access the `meta_info` ?

I think we are calculating this already correctly if I remember right. can you confirm @ifaouibadi?

**Comment by ifaouibadi** [comment]
> I think we are calculating this already correctly if I remember right. can you confirm @ifaouibadi?

Yes we're fetching the token information from https://mainnet.aeternity.io/mdw/aex9/by_name and formatting it based on its decimals

**Pull request merged**
