### PR TITLE
Add aex9 token transfer visualisation

### LINKED ISSUE #29: Display AEX9 tokens

### PR DESCRIPTION
**Pull request by CedrikNikita**
image

fixes #29

### CODE REVIEW

**Review by kenodressel — CHANGES_REQUESTED** [review]
The overview looks a bit bugged, there is no separation line between transactions with token transfers (browser: latest firefox).

image

**Comment by kenodressel** [comment]
image
on http://localhost:3000/transactions/th_2SXrCunqzbFN5Y2tWk7kyuVs6gKNAixuNGfuacSTtczGqkfsQS

**Comment by marc0olo** [comment]
what's the state here? :) @CedrikNikita @kenodressel

**Review by AtanasKrondev — APPROVED** [review]
Looks good to me

**Pull request merged**
