### PR TITLE
feat(account): change allowance display #138

### PR DESCRIPTION
**Pull request by ifaouibadi**

### CODE REVIEW

**Comment by marc0olo** [comment]
image

this reflects also to the "regular tx-view" of an account. I just used the detail view to show you that for "change allowance" the information about the token is quite useless in that sense. if possible we should display:

- token symbol
- amount (allowance)
   - there is probably some logic necessary to show the correct readable value because each token can have different decimals (default is mostly `18`)
- address
    - this is the account that will be allowed to control amount x (allowance) in the name of the address that calls the function of the token contract
    - this address can belong to an account of a contract (which is the case for the DEX related stuff because the user allows the contract to perform token transfers on behalf of himself, needed for swaps)

if this is too cumbersome we can just display the token symbol and change the label (headline) from "ALLOWANCE" to "TOKEN".

I would change remove the `AFFECTED ACCOUNT` (top) and rename the `AFFECTED ACCOUNT` (bottom, which is missing in this view but shown in account tx overview) to `AUTHORIZED` or `AUTHORIZED ACCOUNT`. we already see in the info of `ContractCallTx` who called the entrypoint

**Comment by marc0olo** [comment]
image

seems like we have two different entrypoints for creating or changing the allowance. the label should show the correct action.

@kenodressel @bogdan-manole what's the difference? why to we have a specific `create_allowance` entrypoint?

**Comment by bogdan-manole** [comment]
Is about AEX9 specification:
 - create_allowance is when you create first time the allowance 
 - change_allowance is when you modify the amount of the allowance
[https://github.com/thepiwo/aeternity-fungible-token/blob/de2075772ea90a2e289bcdd003e007f51e80ef71/contracts/extensions/allowances.aes#L90]( https://github.com/thepiwo/aeternity-fungible-token/blob/de2075772ea90a2e289bcdd003e007f51e80ef71/contracts/extensions/allowances.aes#L90)

**Comment by marc0olo** [comment]
image

are we sure that this calculation for the allowance is correct? is that the correct human readable amount based on the decimals of the token contract? I don't think so.

can you verify this again @ifaouibadi? maybe @bogdan-manole or @kenodressel can also give feedback on that.

**Comment by ifaouibadi** [comment]
> are we sure that this calculation for the allowance is correct? is that the correct human readable amount based on the decimals of the token contract? I don't think so.

Fixed

**Review by marc0olo — APPROVED** [review]
looks good to me now!

**Pull request merged**
