### PR TITLE
feat: tokens dedicated page

### LINKED ISSUE #119: introduce dedicated page for AEX-9 tokens
I think we should introduce a dedicated route for AEX-9 tokens where we link to and where token details are displayed:
- contract id
- supply
- decimals
- transfers
- other data that the mdw endpoint provides for each AEX-9 token.

in best case we have an endpoint to get the token distribution. sth. similar to what etherscan provides. we should open a new issue for that of course. @AtanasKrondev can make a proposal what and how to display? if we miss important info from mdw please let me and @thepiwo know.

example:
- https://etherscan.io/token/0xa0b86991c6218b36c1d19d4a2e9eb0ce3606eb48#balances

anyway, I think the token balance display for the very low amount of tokens needs to be fixed.

### PR DESCRIPTION
**Pull request by AtanasKrondev**
Fixes #119

### CODE REVIEW

**Review by marc0olo — CHANGES_REQUESTED** [review]
image

I miss the link to the token-detail page here. this is the main-source why we have this issue :-)

**Comment by marc0olo** [comment]
@AtanasKrondev what happens if there are a lot of holders? would I have to scroll down the whole page to see the transactions?

**Comment by marc0olo** [comment]
@AtanasKrondev I think we should also improve the general token overview. please just show all tokens where symbol starts with `a` when opening the token page.

when can have an alphabet selection then to click through.

example requests:
- `https://mainnet.aeternity.io/mdw/aex9/by_symbol?prefix=a&all`
- `https://mainnet.aeternity.io/mdw/aex9/by_symbol?prefix=b&all`
- `https://mainnet.aeternity.io/mdw/aex9/by_symbol?prefix=c&all`
- ...

Not 100% sure how to deal with special characters in that case. But I think we should avoid loading all tokens at once. But we should have an alphabetical selection to navigate through the token page. I think that makes most sense right now. But am open for other suggestions.

The next step is to also be able to whitelist tokens. I will create a separate issue for that.

**Comment by AtanasKrondev** [comment]
I fixed the missing links to token page from account overview page. In the token page I added a dropdown to choose whether to show holders or transactions.

For now I think it's not a problem to show the whole token list at once - it's pretty light. Of course when this list grows more we should think for filter and/or search, but at this point I think it's not yet necessary.

**Comment by marc0olo** [comment]
@AtanasKrondev thanks for the update!

what do you think about following approach before tackling #122 ?
- show all by default (like currently is)
- provide a separate field to filter by name prefix (typing in "Aet" would filter accordingly)
   - as we already have the complete tokenlist with the first request the filter should work without having to request from middleware again
   - after #122 this could also be applied to the tokenlist and we wouldn't have any difference in the behavior here

before merging this I still have one change request:
- I would like to have the transactions as default selections instead of the holders :-)

also how do we deal with mobile view? maybe we can improve this a bit, see:
image

I think we should avoid scrollbars in mobile view if possible

and one last thing:
- can we provide some user feedback when loading the Tokens view? (loading spinner or sth. like that)

**Review by marc0olo — CHANGES_REQUESTED** [review]
see comment above :-)

**Review by marc0olo — COMMENTED** [review]
I think generally we are fine now. somehow the loading spinner thing isn't working like I expected (see chat on wire)

also loading the token-overview (where alle tokens are listed) takes a very long time. in the beginning I thought the problem is the loading time in the middleware. but this seems to be another issue.

can you investigate this? can you also reproduce it?

**Review by marc0olo — APPROVED** [review]
looks good to me now. the general performance issue will be revisited in another issue

**Pull request merged**
