### PR TITLE
Show token transfers on account page

### LINKED ISSUE #80: Display token transfers on account page
Display the token transfers in account page in similar way as in the single transaction view

Screenshot 2021-08-26 at 12 01 28

Add a filter on account page for different types of transactions

Show "incoming" aex9 transfers

### PR DESCRIPTION
**Pull request by AtanasKrondev**
Fixes #80 

Token transactions are shown on account page
Screenshot 2021-09-03 at 11 51 14

Added AEX9 transactions filters
Screenshot 2021-09-03 at 11 51 14
Screenshot 2021-09-03 at 11 51 14
Screenshot 2021-09-03 at 11 51 14

### CODE REVIEW

**Review by marc0olo — CHANGES_REQUESTED** [review]
image

getting this error when trying to filter for AEX-9 transactions on the "regular transaction view". when I am looking into an account everything works fine.

I also think that in the "regular transaction view" a filter for AEX-9 in general (without sent/received) is more convenient as we haven't selected an account in that case.

can you adapt and improve that? thanks :-)

**Comment by marc0olo** [comment]
not sure if this is related to that issue here: https://github.com/aeternity/aepp-sdk-js/issues/1266

**Comment by AtanasKrondev** [comment]
@marc0olo I removed the irrelevant AEX9 filters on all transactions view, which caused errors. Also fixed a problem with the pagination on account transactions view filters pagination.

Is there an endpoint in the middleware fetching all AEX9 transactions, without specifying sender or receiver, as I didn't found one?

commit 94dfc1ccdb941f80e06a559c26a7d7a274afcdd8 adds tokens info when you filter "contract_call" on all transactions view. I'm not sure about this one because it's incredibly slow, due to the multiple calls to the mdw, fetching additional info for the tokens.

**Comment by marc0olo** [comment]
> Is there an endpoint in the middleware fetching all AEX9 transactions, without specifying sender or receiver, as I didn't found one?

@thepiwo @sborrazas @jyeshe @wj2016 do we have such an endpoint? if not we should consider it in my opinion.

> commit [94dfc1c](https://github.com/aeternity/mdw-frontend/commit/94dfc1ccdb941f80e06a559c26a7d7a274afcdd8) adds tokens info when you filter "contract_call" on all transactions view. I'm not sure about this one because it's incredibly slow, due to the multiple calls to the mdw, fetching additional info for the tokens.

do I understand that you implemented it like this due to the fact that there is no easy way to receive all AEX9 transactions? IMO we should rollback this until this is possible then. it takes very long to load the contract calls now and we don't have the possibility to filter for AEX-9 token transfers exclusively.

@AtanasKrondev I have no idea what's going on there but when clicking on an address for the token-transfer in that filtered contract-call view in transactions there are many requests happening to fetch the token-transfers for that specific address
image

probably this will be solved if we rollback these changes.

next time it would be better to discuss that before :) personally I would favor a dedicated endpoint to fetch and/or filter all AEX9 transactions, regardless the accounts

**Comment by marc0olo** [comment]
image

@AtanasKrondev it turns out that the same endpoint is called 11 times when viewing the transactions of an account. why is it like that? it currently takes ~40 seconds for me to see the transactions of an account

**Comment by marc0olo** [comment]
looks good to me now. thanks @AtanasKrondev !

**Review by marc0olo — APPROVED** [review]

**Pull request merged**
